Repository pingcap/autoflow, pull requests merged in 2024-08, with the labels that each got.

#231 feat: show message stream state history
  backend/app/rag/chat.py
  backend/app/rag/chat_stream_protocol.py
  backend/app/rag/knowledge_graph/base.py
  e2e/global.setup.ts
  e2e/playwright.config.ts
  e2e/tests/bootstrap.ts
  e2e/tests/global.setup.ts
  frontend/app/package.json
  frontend/app/src/components/chat/chat-hooks.tsx
  frontend/app/src/components/chat/chat-message-controller.ts
  frontend/app/src/components/chat/chat-stream-state.ts
  frontend/app/src/components/chat/conversation-message-groups.tsx
  frontend/app/src/components/chat/message-annotation-history.tsx
  frontend/app/src/components/chat/message-annotation.test.tsx
  frontend/app/src/components/chat/message-annotation.tsx
  frontend/app/src/components/chat/message-answer.tsx
  frontend/app/src/components/chat/message-content-sources.tsx
  frontend/app/src/components/chat/message-heading.tsx
  frontend/app/src/components/chat/message-section.tsx
  frontend/app/src/components/chat/utils.ts
  frontend/app/src/components/diff-seconds.tsx
  frontend/packages/widget-react/src/App.tsx
  frontend/pnpm-lock.yaml
Labels: do-not-merge/hold, require-build

#236 feat(frontend): experimental chat message verify step
  frontend/app/package.json
  frontend/app/src/components/chat/chat-hooks.tsx
  frontend/app/src/components/chat/conversation-message-groups.tsx
  frontend/app/src/experimental/chat-verify-service/api.ts
  frontend/app/src/experimental/chat-verify-service/message-verify.tsx
  frontend/app/src/lib/request.ts
Labels: require-build

#238 release 0.2.0
  .env.example
  docker-compose.yml
  frontend/app/src/pages/docs/deploy-with-docker.mdx
  releases/v0.2.0.md
Labels: do-not-merge/hold

#245 feat(frontend): support retry datasource failed tasks
  frontend/app/src/api/datasources.ts
  frontend/app/src/app/(main)/(admin)/datasources/[id]/page.tsx
  frontend/app/src/components/datasource/DatasourceDetails.tsx
  frontend/app/src/components/datasource/DatasourceName.tsx
  frontend/app/src/components/datasource/hooks.ts
Labels: require-build

#247 feat(backend): support ollama llm; support ollama, jina, cohere embedding
  .env.example
  backend/app/alembic/versions/00534dc350db_.py
  backend/app/alembic/versions/2fc10c21bf88_.py
  backend/app/api/admin_routes/llm.py
  backend/app/core/config.py
  backend/app/models/chunk.py
  backend/app/models/embed_model.py
  backend/app/models/knowledge_graph.py
  backend/app/models/llm.py
  backend/app/models/reranker_model.py
  backend/app/models/semantic_cache.py
  backend/app/rag/build.py
  backend/app/rag/chat_config.py
  backend/app/rag/embed_model_option.py
  backend/app/rag/llm_option.py
  backend/app/rag/vector_store/tidb_vector_store.py
  backend/app/types.py
  backend/app/utils/dspy.py
  backend/pyproject.toml
  backend/requirements-dev.lock
  backend/requirements.lock
Labels: require-build

#249 feat(backend): support local embedding & reranker
  backend/app/rag/chat_config.py
  backend/app/rag/embed_model_option.py
  backend/app/rag/embeddings/__init__.py
  backend/app/rag/embeddings/local_embedding.py
  backend/app/rag/node_postprocessor/local_reranker.py
  backend/app/rag/reranker_model_option.py
  backend/app/types.py
  backend/local_embedding_reranker/.dockerignore
  backend/local_embedding_reranker/Dockerfile
  backend/local_embedding_reranker/main.py
  backend/local_embedding_reranker/requirements.txt
Labels: require-build

#251 feat(widget): support controlled api and custom trigger button
  frontend/app/package.json
  frontend/app/src/api/chats.ts
  frontend/app/src/api/site-settings.ts
  frontend/app/src/api/system.ts
  frontend/app/src/lib/request.ts
  frontend/app/src/lib/request/authenticationHeaders.mock.ts
  frontend/app/src/lib/request/authenticationHeaders.react-server.ts
  frontend/app/src/lib/request/authenticationHeaders.ts
  frontend/app/src/lib/request/base-url.ts
  frontend/app/src/lib/request/errors.ts
  frontend/app/src/lib/request/index.ts
  frontend/app/src/lib/request/params.ts
  frontend/app/src/lib/request/response-handlers.ts
  frontend/app/src/lib/zod.ts
  frontend/packages/widget-react/USAGE.md
  frontend/packages/widget-react/demo.html
  frontend/packages/widget-react/index.html
  frontend/packages/widget-react/src/App.tsx
  frontend/packages/widget-react/src/Widget.css
  frontend/packages/widget-react/src/Widget.tsx
  frontend/packages/widget-react/src/assets/react.svg
  frontend/packages/widget-react/src/library.tsx
  frontend/packages/widget-react/src/load-config.ts
  frontend/packages/widget-react/src/main.tsx
  frontend/packages/widget-react/src/overrides/components/chat/style.css
  frontend/packages/widget-react/src/overrides/components/code-theme.scss
  frontend/packages/widget-react/src/overrides/components/remark-content/style.scss
  frontend/packages/widget-react/src/overrides/next/headers.ts
  frontend/packages/widget-react/vite.config.ts
Labels: require-build

#253 use external request id to reduce validate job
  frontend/app/src/experimental/chat-verify-service/api.ts
  frontend/app/src/experimental/chat-verify-service/message-verify.tsx
Labels: require-build

#252 e2e: simple case for js widget
  e2e/.env.backend
  e2e/.env.frontend
  e2e/docker-compose.yml
  e2e/tests/widget.spec.ts
Labels: require-build
