Repository pingcap/autoflow, pull requests merged in 2024-12, with the labels that each got.

#434 e2e: use tidbcloud serverless
  .github/workflows/release.yml
  e2e/.env.backend
  e2e/.gitignore
  e2e/docker-compose.yml
  e2e/package-lock.json
  e2e/package.json
  e2e/prepare-test.sh
  e2e/scripts/create-temp-serverless-cluster.mjs
  e2e/scripts/drop-temp-serverless-cluster.mjs
  e2e/start-test.sh
Labels: require-build, e2e-frontend:branch-main, e2e-backend:branch-main

#443 fix: remove useless files, fix need_migration, and refine codes
  backend/app/api/admin_routes/data_source.py
  backend/app/api/admin_routes/embedding_model/routes.py
  backend/app/api/admin_routes/graph_editor.py
  backend/app/api/admin_routes/knowledge_base/data_source/__init__.py
  backend/app/api/admin_routes/knowledge_base/data_source/models.py
  backend/app/api/admin_routes/knowledge_base/data_source/routes.py
  backend/app/api/admin_routes/knowledge_base/graph/models.py
  backend/app/api/admin_routes/knowledge_base/graph/routes.py
  backend/app/api/admin_routes/knowledge_base/models.py
  backend/app/api/admin_routes/knowledge_base/routes.py
  backend/app/api/admin_routes/langfuse.py
  backend/app/api/admin_routes/llm.py
  backend/app/api/admin_routes/llm/__init__.py
  backend/app/api/admin_routes/llm/routes.py
  backend/app/api/admin_routes/rag_index.py
  backend/app/api/admin_routes/reranker_model/__init__.py
  backend/app/api/admin_routes/reranker_model/routes.py
  backend/app/api/admin_routes/retrieve.py
  backend/app/api/main.py
  backend/app/api/routes/chat.py
  backend/app/api/routes/models.py
  backend/app/exceptions.py
  backend/app/models/knowledge_base.py
  backend/app/rag/build.py
  backend/app/rag/chat.py
  backend/app/rag/chat_config.py
  backend/app/rag/knowledge_base/config.py
  backend/app/rag/retrieve.py
  backend/app/repositories/base_repo.py
  backend/app/repositories/embedding_model.py
  backend/app/repositories/knowledge_base.py
  backend/app/repositories/llm.py
  backend/app/repositories/reranker_model.py
  backend/app/tasks/__init__.py
  backend/app/tasks/datasource.py
  backend/app/tasks/knowledge_base.py
  backend/app/tasks/rag_build.py
  frontend/.prettierignore
  frontend/app/src/api/system.ts
  frontend/app/src/components/system/BootstrapStatusProvider.tsx
  frontend/app/src/components/ui/sidebar.tsx
Labels: require-build

#414 feat: support knowledge base delete document API
  backend/app/api/admin_routes/document/routes.py
  backend/app/api/admin_routes/knowledge_base/data_source/routes.py
  backend/app/api/admin_routes/knowledge_base/document/__init__.py
  backend/app/api/admin_routes/knowledge_base/document/models.py
  backend/app/api/admin_routes/knowledge_base/document/routes.py
  backend/app/api/admin_routes/knowledge_base/routes.py
  backend/app/api/main.py
  backend/app/api/routes/chat.py
  backend/app/exceptions.py
  backend/app/rag/chat.py
  backend/app/repositories/chat_engine.py
  backend/app/repositories/chunk.py
  backend/app/repositories/document.py
  backend/app/repositories/embedding_model.py
  backend/app/repositories/entity.py
  backend/app/repositories/graph.py
  backend/app/repositories/knowledge_base.py
  backend/app/repositories/llm.py
  backend/app/repositories/relationship.py
  backend/app/tasks/knowledge_base.py
Labels: require-build

#404 docs: prepare 0.3 release notes
  backend/app/rag/embed_model_option.py
  frontend/app/src/app/(main)/(admin)/knowledge-bases/[id]/(special)/data-sources/new/page.tsx
  frontend/app/src/app/(main)/(admin)/knowledge-bases/[id]/(special)/documents/[documentId]/chunks/page.tsx
  frontend/app/src/app/(main)/(admin)/knowledge-bases/[id]/(tabs)/layout.tsx
  frontend/app/src/app/(main)/(admin)/knowledge-bases/page.tsx
  frontend/app/src/components/ui/sidebar.tsx
  frontend/app/src/pages/docs/_meta.ts
  frontend/app/src/pages/docs/data-source.mdx
  frontend/app/src/pages/docs/deploy-with-docker.mdx
  frontend/app/src/pages/docs/embedding-model.mdx
  frontend/app/src/pages/docs/knowledge-base.mdx
  frontend/app/src/pages/docs/quick-start.mdx
  frontend/app/src/pages/docs/requirements.mdx
  releases/v0.3.0.md
Labels: do-not-merge/hold

#488 chore(frontend): upgrade to nextjs 15 + react 19
  .github/workflows/release.yml
  e2e/tests/bootstrap.ts
  frontend/app/myenv.d.ts
  frontend/app/next.config.mjs
  frontend/app/next.config.ts
  frontend/app/package.json
  frontend/app/src/app/(main)/(.)auth/login/page.tsx
  frontend/app/src/app/(main)/(admin)/chat-engines/[id]/page.tsx
  frontend/app/src/app/(main)/(admin)/embedding-models/[id]/page.tsx
  frontend/app/src/app/(main)/(admin)/knowledge-bases/[id]/(special)/data-sources/new/page.tsx
  frontend/app/src/app/(main)/(admin)/knowledge-bases/[id]/(special)/documents/[documentId]/chunks/page.tsx
  frontend/app/src/app/(main)/(admin)/knowledge-bases/[id]/(tabs)/data-sources/page.tsx
  frontend/app/src/app/(main)/(admin)/knowledge-bases/[id]/(tabs)/index-progress/page.tsx
  frontend/app/src/app/(main)/(admin)/knowledge-bases/[id]/(tabs)/knowledge-graph-explorer/create-synopsis-entity/page.tsx
  frontend/app/src/app/(main)/(admin)/knowledge-bases/[id]/(tabs)/knowledge-graph-explorer/page.tsx
  frontend/app/src/app/(main)/(admin)/knowledge-bases/[id]/(tabs)/layout.tsx
  frontend/app/src/app/(main)/(admin)/knowledge-bases/[id]/(tabs)/page.tsx
  frontend/app/src/app/(main)/(admin)/knowledge-bases/[id]/(tabs)/settings/page.tsx
  frontend/app/src/app/(main)/(admin)/llms/[id]/page.tsx
  frontend/app/src/app/(main)/(admin)/reranker-models/[id]/page.tsx
  frontend/app/src/app/(main)/c/[id]/page.tsx
  frontend/app/src/app/auth/login/page.tsx
  frontend/app/src/components/auto-scroll/auto-scroll.stories.tsx
  frontend/app/src/components/cells/metadata.tsx
  frontend/app/src/components/chat/use-ask.ts
  frontend/app/src/components/form/control-widget.tsx
  frontend/app/src/components/form/widgets/CodeInput.tsx
  frontend/app/src/components/graph/components/JsonField.tsx
  frontend/app/src/components/remark-content/components.tsx
  frontend/app/src/components/settings/SettingsField.tsx
  frontend/app/src/components/site-nav.tsx
  frontend/app/src/components/ui/form.ext.tsx
  frontend/app/src/experimental/chat-verify-service/message-verify.tsx
  frontend/app/src/lib/request/authenticationHeaders.react-server.ts
  frontend/app/tsconfig.json
  frontend/package.json
  frontend/packages/widget-react/package.json
  frontend/pnpm-lock.yaml
Labels: require-build, e2e-backend:branch-main

#492 fix(frontend): refresh after navigating
  frontend/app/src/app/(main)/(admin)/embedding-models/create/page.tsx
  frontend/app/src/app/(main)/(admin)/llms/create/page.tsx
  frontend/app/src/app/(main)/(admin)/reranker-models/create/page.tsx
  frontend/app/src/components/chat-engine/create-chat-engine-form.tsx
  frontend/app/src/components/embedding-models/EmbeddingModelsTable.tsx
  frontend/app/src/components/knowledge-base/create-knowledge-base-form.tsx
  frontend/app/src/components/llm/LLMsTable.tsx
  frontend/app/src/components/reranker/RerankerModelsTable.tsx
Labels: require-build, e2e-backend:branch-main

#503 add verification for stackvm
  backend/app/rag/chat.py
Labels: require-build

#504 support response format
  backend/app/rag/chat.py
  backend/app/rag/utils.py
  backend/app/repositories/chat.py
Labels: require-build

#498 fix: staging errors
  backend/app/api/admin_routes/evaluation/evaluation_task.py
  backend/app/tasks/evaluate.py
Labels: require-build

#515 feat: update evaluation api group
  backend/app/api/admin_routes/evaluation/evaluation_dataset.py
  backend/app/api/admin_routes/evaluation/evaluation_task.py
  backend/app/api/admin_routes/evaluation/models.py
  backend/app/api/admin_routes/upload.py
  backend/app/auth/users.py
  backend/app/models/evaluation_task.py
  backend/app/rag/chat.py
  backend/app/rag/utils.py
  backend/app/repositories/chat.py
  backend/app/tasks/evaluate.py
  backend/bootstrap.py
Labels: require-build

#517 Extend graph search capabilities
  backend/app/api/admin_routes/knowledge_base/graph/models.py
  backend/app/api/admin_routes/knowledge_base/graph/routes.py
  backend/app/rag/knowledge_graph/graph_store/tidb_graph_store.py
Labels: require-build

#521 Improve graph basic api
  backend/app/rag/knowledge_graph/graph_store/tidb_graph_store.py
Labels: require-build

#524 refactor(frontend): replace react-hook-form with @tanstack/form
  e2e/tests/bootstrap.ts
  frontend/app/src/api/documents.ts
  frontend/app/src/api/embedding-models.ts
  frontend/app/src/api/evaluations.ts
  frontend/app/src/api/rerankers.ts
  frontend/app/src/components/api-keys/CreateApiKeyForm.tsx
  frontend/app/src/components/chat-engine/create-chat-engine-form.tsx
  frontend/app/src/components/chat-engine/update-chat-engine-form.tsx
  frontend/app/src/components/datasource/create-datasource-form.tsx
  frontend/app/src/components/datasource/datasource-card.tsx
  frontend/app/src/components/datasource/update-datasource-form.tsx
  frontend/app/src/components/documents/documents-table-filters.tsx
  frontend/app/src/components/embedding-models/CreateEmbeddingModelForm.tsx
  frontend/app/src/components/evaluations/create-evaluation-dataset-form.tsx
  frontend/app/src/components/evaluations/create-evaluation-dataset-item-form.tsx
  frontend/app/src/components/evaluations/create-evaluation-task-form.tsx
  frontend/app/src/components/evaluations/evaluation-dataset-info.tsx
  frontend/app/src/components/evaluations/evaluation-task-info.stories.tsx
  frontend/app/src/components/evaluations/evaluation-task-info.tsx
  frontend/app/src/components/evaluations/evaluation-tasks-table.tsx
  frontend/app/src/components/evaluations/keyword-filter-toolbar.tsx
  frontend/app/src/components/evaluations/update-evaluation-dataset-item-form.tsx
  frontend/app/src/components/form-sections.tsx
  frontend/app/src/components/form/biz.tsx
  frontend/app/src/components/form/control-widget.tsx
  frontend/app/src/components/form/create-entity-form.tsx
  frontend/app/src/components/form/field-layout.beta.tsx
  frontend/app/src/components/form/field-layout.tsx
  frontend/app/src/components/form/root-error.tsx
  frontend/app/src/components/form/submit.tsx
  frontend/app/src/components/form/utils.ts
  frontend/app/src/components/form/widgets/CodeInput.tsx
  frontend/app/src/components/form/widgets/FileInput.tsx
  frontend/app/src/components/form/widgets/FilesInput.tsx
  frontend/app/src/components/form/widgets/PromptInput.tsx
  frontend/app/src/components/graph/GraphCreateEntity.tsx
  frontend/app/src/components/graph/components/SearchEntity.tsx
  frontend/app/src/components/graph/components/SearchEntityById.tsx
  frontend/app/src/components/knowledge-base/create-knowledge-base-form.tsx
  frontend/app/src/components/knowledge-base/form-index-methods.tsx
  frontend/app/src/components/knowledge-base/hooks.ts
  frontend/app/src/components/knowledge-base/knowledge-base-settings-form.tsx
  frontend/app/src/components/llm/CreateLLMForm.tsx
  frontend/app/src/components/reranker/CreateRerankerForm.tsx
  frontend/app/src/components/settings-form/GeneralSettingsField.tsx
  frontend/app/src/components/settings-form/GeneralSettingsForm.tsx
  frontend/app/src/components/settings-form/context.tsx
  frontend/app/src/components/settings/LinkArrayField.tsx
  frontend/app/src/components/settings/SettingsField.tsx
  frontend/app/src/components/settings/StringArrayField.tsx
  frontend/app/src/components/signin.tsx
  frontend/app/src/components/ui/form.beta.tsx
  frontend/app/src/hooks/use-model-provider.ts
  frontend/app/src/lib/react.ts
  frontend/app/src/lib/tanstack-form.ts
Labels: require-build, e2e-backend:branch-main

#530 Refine the goal background generation and api
  backend/app/rag/knowledge_graph/graph_store/tidb_graph_store.py
Labels: require-build

#529 e2e: add new chat engine tests
  e2e/docker-compose.yml
  e2e/prepare-test.sh
  e2e/start-test.sh
  e2e/tests/chat-engine.spec.ts
Labels: require-build, e2e-frontend:branch-main, e2e-backend:branch-main

#533 fix(frontend): fix widget display conditions
  frontend/packages/widget-react/src/Widget.tsx
  frontend/packages/widget-react/src/library.tsx
Labels: require-build, e2e-backend:branch-main

#536 e2e: add knowledge base test cases
  e2e/playwright.config.ts
  e2e/tests/chat-engine.spec.ts
  e2e/tests/knowledge-base.spec.ts
  e2e/utils/forms.ts
Labels: require-build, e2e-frontend:branch-main, e2e-backend:branch-main

#543 Fix embedding model bug and support arm platform
  backend/app/rag/embeddings/openai_like_embedding.py
  backend/app/rag/knowledge_graph/graph_store/tidb_graph_store.py
  backend/app/tasks/build_index.py
Labels: require-build

#546 fix bug of merging entities
  backend/app/rag/knowledge_graph/graph_store/tidb_graph_store.py
Labels: require-build

#544 e2e: add evaluation dataset test cases
  e2e/res/sample-evaluation-dataset.csv
  e2e/res/sample.pdf
  e2e/tests/api-keys.spec.ts
  e2e/tests/bootstrap.ts
  e2e/tests/evaluation.spec.ts
  e2e/tests/knowledge-base.spec.ts
Labels: require-build, e2e-frontend:branch-main, e2e-backend:branch-main

#553 feat(frontend): support download uploaded files
  frontend/app/src/components/chat/message-content-sources.tsx
  frontend/app/src/components/chat/utils.ts
  frontend/app/src/components/documents/documents-table.tsx
Labels: require-build, e2e-backend:branch-main
