Repository pingcap/autoflow, pull requests merged in 2024-10, with the labels that each got.

#317 add pure embedding retrieve api
  backend/app/api/admin_routes/retrieve.py
  backend/app/rag/retrieve.py
Labels: require-build

#318 add embedding_retrieve api test
  e2e/tests/api.spec.ts
Labels: require-build

#319 add current to text qa prompt
  backend/app/rag/chat.py
  backend/app/rag/default_prompt.py
Labels: require-build

#325 feat: add more ways to filter the docs during searching
  backend/app/api/admin_routes/document.py
  backend/app/api/admin_routes/retrieve.py
  backend/app/repositories/document.py
  e2e/tests/api.spec.ts
Labels: require-build, e2e-frontend:branch-main

#326 feat(frontend): support datasource filtering
  frontend/app/src/api/documents.ts
  frontend/app/src/api/rag.ts
  frontend/app/src/components/data-table-remote.tsx
  frontend/app/src/components/documents/documents-table-filters.tsx
  frontend/app/src/components/documents/documents-table.tsx
  frontend/app/src/lib/request/params.ts
Labels: require-build, e2e-backend:pr-325

#331 feat: recommend questions api
  backend/app/alembic/versions/749767db5505_add_recommend_questions.py
  backend/app/api/admin_routes/document.py
  backend/app/api/routes/chat.py
  backend/app/models/__init__.py
  backend/app/models/recommend_question.py
  backend/app/rag/chat.py
  backend/app/rag/chat_config.py
  backend/app/rag/default_prompt.py
Labels: require-build, e2e-frontend:branch-main

#337 fix: save message body to db
  backend/app/rag/chat.py
Labels: require-build

#338 feat(backend): support upload excel
  backend/app/api/admin_routes/upload.py
  backend/app/rag/datasource/file.py
  backend/app/types.py
  backend/pyproject.toml
  backend/requirements-dev.lock
  backend/requirements.lock
  frontend/app/src/api/documents.ts
  frontend/app/src/components/datasource/CreateFileDatasourceForm.tsx
Labels: require-build

#336 feat(frontend): stackvm chat engine
  frontend/app/.env
  frontend/app/jest.config.ts
  frontend/app/package.json
  frontend/app/src/api/chat-engines.ts
  frontend/app/src/components/chat/chat-controller.ts
  frontend/app/src/components/chat/chat-hooks.tsx
  frontend/app/src/components/chat/chat-message-controller.test.ts
  frontend/app/src/components/chat/chat-message-controller.ts
  frontend/app/src/components/chat/chat-new-dialog.tsx
  frontend/app/src/components/chat/chat-stream-state.ts
  frontend/app/src/components/chat/conversation-message-groups.tsx
  frontend/app/src/components/chat/knowledge-graph-debug-info.tsx
  frontend/app/src/components/chat/message-annotation-history-stackvm.tsx
  frontend/app/src/components/chat/message-annotation-history.tsx
  frontend/app/src/components/chat/message-auto-scroll.tsx
  frontend/app/src/components/chat/message-content.test.tsx
  frontend/app/src/components/chat/utils.ts
  frontend/app/src/components/remark-content/remark-content.tsx
  frontend/app/src/experimental/chat-verify-service/message-verify.stories.tsx
  frontend/app/src/lib/stackvm/core/index.ts
  frontend/app/src/lib/stackvm/core/instructions/index.ts
  frontend/app/src/lib/stackvm/core/instructions/instructions.ts
  frontend/app/src/lib/stackvm/core/instructions/registry.ts
  frontend/app/src/lib/stackvm/core/model.ts
  frontend/app/src/lib/stackvm/core/types.ts
  frontend/app/src/lib/stackvm/core/visit.ts
  frontend/app/src/lib/stackvm/index.ts
  frontend/app/src/lib/strings.ts
  frontend/pnpm-lock.yaml
Labels: require-build

#332 feat(frontend): show further questions
  frontend/app/.env
  frontend/app/src/api/chats.ts
  frontend/app/src/components/chat/chat-hooks.tsx
  frontend/app/src/components/chat/conversation-message-groups.tsx
  frontend/app/src/components/chat/message-operations.tsx
  frontend/app/src/components/chat/message-recommend-questions.tsx
Labels: require-build

#349 feat: support hide sources
  backend/app/rag/chat_config.py
  frontend/app/src/api/chat-engines.ts
  frontend/app/src/components/chat-engine/chat-engine-options-details.tsx
  frontend/app/src/components/chat-engine/edit-option-boolean-form.tsx
  frontend/app/src/components/chat/conversation-message-groups.tsx
Labels: require-build

#342 add question refinement before call stackvm
  backend/app/rag/chat.py
  frontend/app/src/components/chat/chat-message-controller.ts
  frontend/app/src/components/chat/chat-stream-state.ts
  frontend/app/src/components/chat/message-annotation-history-stackvm.tsx
Labels: require-build

#353 api: add chat origin to /feedbacks
  backend/app/api/admin_routes/feedback.py
  backend/app/models/feedback.py
  frontend/app/src/api/feedbacks.ts
  frontend/app/src/components/feedbacks/feedbacks-table.tsx
Labels: require-build

#356 Refine agent answer
  backend/app/alembic/versions/c7f016a904c1_.py
  backend/app/models/chat_message.py
  backend/app/rag/chat.py
  backend/app/rag/chat_config.py
  backend/app/rag/default_prompt.py
Labels: require-build

#358 enhance goal generation
  backend/app/rag/chat.py
  backend/app/rag/chat_config.py
  backend/app/rag/default_prompt.py
Labels: require-build

#359 feat: clarifying question
  backend/app/rag/chat.py
  backend/app/rag/chat_config.py
  backend/app/rag/default_prompt.py
  backend/app/rag/types.py
  backend/requirements-dev.lock
  backend/requirements.lock
Labels: require-build
